# Author : Jakub Bartodziej <kubabartodziej@gmail.com>
# The theme uses the gruvbox dark palette with standard contrast: github.com/morhetz/gruvbox

"annotation" = { fg = "fg1" }

"attribute" = { fg = "aqua1" }

"comment" = { fg = "gray" }

"constant" = { fg = "purple1" }
"constant.character" = { fg = "aqua1" }
"constant.character.escape" = { fg = "orange1" }
"constant.macro" = { fg = "aqua1" }
"constructor" = { fg = "purple1" }

"definition" = { underline = { color = "aqua1" } }

"diagnostic" = { underline = { color = "orange1", style = "curl" } }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"diagnostic.error" = { underline = { color = "red1", style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue1", style = "curl" } }
"diagnostic.info" = { underline = { color = "aqua1", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow1", style = "curl" } }
# "diagnostic.unnecessary" = { modifiers = ["dim"] }  # do not remove this for future resolving

"error" = { fg = "red1" }
"hint" = { fg = "blue1" }
"info" = { fg = "aqua1" }
"warning" = { fg = "yellow1" }

"diff.delta" = { fg = "yellow1" }
"diff.minus" = { fg = "red1" }
"diff.plus" = { fg = "green1" }

"function" = { fg = "green1" }
"function.builtin" = { fg = "yellow1" }
"function.macro" = { fg = "blue1" }

"keyword" = { fg = "red1" }
"keyword.control.import" = { fg = "aqua1" }

"label" = { fg = "red1" }

"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = "aqua1"
"markup.link.text" = "red1"
"markup.link.url" = { fg = "green1", modifiers = ["underlined"] }
"markup.raw" = "red1"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"module" = { fg = "aqua1" }

"namespace" = { fg = "fg1" }

"operator" = { fg = "purple1" }

"punctuation" = { fg = "orange1" }

"special" = { fg = "purple0" }

"string" = { fg = "green1" }
"string.regexp" = { fg = "orange1" }
"string.special" = { fg = "orange1" }
"string.symbol" = { fg = "yellow1" }

"tag" = { fg = "aqua1" }

"type" = { fg = "yellow1" }

"ui.background" = { bg = "bg0" }
"ui.bufferline" = { fg = "fg1", bg = "bg1" }
"ui.bufferline.active" = { fg = "bg0", bg = "yellow0" }
"ui.bufferline.background" = { bg = "bg2" }

"ui.cursor" = { fg = "bg1", bg = "bg2" }
"ui.cursor.insert" = { fg = "bg1", bg = "accent" }
"ui.cursor.normal" = { fg = "bg1", bg = "gray" }
"ui.cursor.select" = { fg = "bg1"}
"ui.cursor.match" = { fg = "fg3", bg = "bg3" }

"ui.cursor.primary" = { bg = "fg3", fg = "bg1" }
"ui.cursor.primary.insert" = { fg = "bg1", bg = "accent" }
"ui.cursor.primary.normal" = { fg = "bg0", bg = "fg3" }
"ui.cursor.primary.select" = { fg = "fg1", bg = "bg3" }

"ui.cursorline" = { bg = "bg0_s" }
"ui.cursorline.primary" = { bg = "bg1" }

"ui.help" = { bg = "bg1", fg = "fg1" }
"ui.linenr" = { fg = "bg3" }
"ui.linenr.selected" = { fg = "yellow1" }
"ui.menu" = { fg = "fg1", bg = "bg2" }
"ui.menu.selected" = { fg = "bg2", bg = "blue1", modifiers = ["bold"] }
"ui.popup" = { bg = "bg1" }
"ui.picker.header.column" = { underline.style = "line" }
"ui.picker.header.column.active" = { modifiers = ["bold"], underline.style = "line" }
"ui.selection" = { fg = "bg1", bg = "fg3" }
"ui.selection.primary" = { fg = "fg1", bg = "bg2" }

"ui.statusline" = { fg = "fg1", bg = "bg2" }
"ui.statusline.inactive" = { fg = "fg4", bg = "bg2" }
"ui.statusline.insert" = { fg = "bg1", bg = "blue1", modifiers = ["bold"] }
"ui.statusline.normal" = { fg = "bg1", bg = "fg3", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg1", bg = "orange1", modifiers = ["bold"] }

"ui.text" = { fg = "fg1" }
"ui.text.focus" = { fg = "green1" }
"ui.text.directory" = { fg = "blue1" }
"ui.virtual.inlay-hint" = { fg = "gray" }
"ui.virtual.jump-label" = { fg = "purple0", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.whitespace" = "bg2"
"ui.virtual.wrap" = { fg = "bg2" }
"ui.window" = { bg = "bg1" }

"variable" = { fg = "fg1" }
"variable.builtin" = { fg = "orange1" }
"variable.other.member" = { fg = "blue1" }
"variable.parameter" = { fg = "blue1" }


[palette]
bg0 = "#1C1B1A"   # main background
bg0_s = "#282726"
bg1 = "#343331"
bg2 = "#403E3C"
bg3 = "#575653"
bg4 = "#6F6E69"

fg0 = "#DAD8CE"
fg1 = "#CECDC3" # main foreground
fg2 = "#878580"
fg3 = "#6F6E69"
fg4 = "#575653"

gray = "#878580"
accent = "#4385BE"
red0 = "#6F6E69"    # neutral
red1 = "#575653"    # bright
green0 = "#575653"
green1 = "#575653"
yellow0 = "#878580"
yellow1 = "#878580"
blue0 = "#6F6E69"
blue1 = "#878580"
purple0 = "#CECDC3"
purple1 = "#575653"
aqua0 = "#878580"
aqua1 = "#CECDC3"
orange0 = "#575653"
orange1 = "#878580"
